### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by caillou** [upfrontIO/livingdocs-manager#26]
Here is a problem that happened, where the error message does not really tell us anything:

```
ldm project:design:add --version 0.4.3 --name timeline

ERR! project:design:add Error: Unhandled response code 500
ERR! project:design:add   at Object.module.exports.api.requestError (/Users/caillou/.nvm/versions/node/v4.2.2/lib/node_modules/livingdocs-manager/lib/api/index.coffee:19:17)
ERR! project:design:add   at Request._callback (/Users/caillou/.nvm/versions/node/v4.2.2/lib/node_modules/livingdocs-manager/lib/api/index.coffee:180:20)
ERR! project:design:add   at Request.self.callback (/Users/caillou/.nvm/versions/node/v4.2.2/lib/node_modules/livingdocs-manager/node_modules/request/request.js:197:22)
ERR! project:design:add   at emitTwo (events.js:87:13)
ERR! project:design:add   at Request.emit (events.js:172:7)
ERR! project:design:add   at Request.<anonymous> (/Users/caillou/.nvm/versions/node/v4.2.2/lib/node_modules/livingdocs-manager/node_modules/request/request.js:1050:14)
ERR! project:design:add   at emitOne (events.js:82:20)
ERR! project:design:add   at Request.emit (events.js:169:7)
ERR! project:design:add   at IncomingMessage.<anonymous> (/Users/caillou/.nvm/versions/node/v4.2.2/lib/node_modules/livingdocs-manager/node_modules/request/request.js:996:12)
ERR! project:design:add   at emitNone (events.js:72:20)
ERR! project:design:add   at IncomingMessage.emit (events.js:166:7)
ERR! project:design:add   at endReadableNT (_stream_readable.js:905:12)
ERR! project:design:add   at doNTCallback2 (node.js:441:9)
ERR! project:design:add   at process._tickCallback (node.js:355:17)
ERR! project:design:add
ERR! project:design:add  { [Error: Unhandled response code 500]
ERR! project:design:add   status: 500,
ERR! project:design:add   request:
ERR! project:design:add    { url: 'http://localhost:9090/projects/1/add-design',
ERR! project:design:add      method: 'post',
ERR! project:design:add      headers:
ERR! project:design:add       { Authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJlMDA2NGYyZC1hNTBlLTQ3MDUtYWE0Yy05MjY1MWFmZjVlMGUiLCJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNDUzMjg0OTAyLCJleHAiOjE0NTMzMjgxMDF9.XZdO4Gupzslv4gDUM20efTjyo8IsCM8dCRNpgLQ_d1c',
ERR! project:design:add         accept: 'application/json',
ERR! project:design:add         'content-type': 'application/json',
ERR! project:design:add         'content-length': 37 },
ERR! project:design:add      body: 'Invalid statusCode 500' },
ERR! project:design:add   response:
ERR! project:design:add    { statusCode: 500,
ERR! project:design:add      body:
ERR! project:design:add       { status: 500,
ERR! project:design:add         error: 'Internal Server Error',
ERR! project:design:add         error_details: [Object] },
ERR! project:design:add      headers:
ERR! project:design:add       { 'x-request-id': '355b76e6-5639-4517-8af2-9cd9a97c2048',
ERR! project:design:add         'access-control-allow-origin': '*',
ERR! project:design:add         'access-control-allow-methods': 'OPTIONS, GET, PUT, POST, PATCH, DELETE',
ERR! project:design:add         'content-type': 'application/json; charset=utf-8',
ERR! project:design:add         'content-length': '3098',
ERR! project:design:add         etag: 'W/"c1a-x2anVAGefcY+mjGW0Yt1NA"',
ERR! project:design:add         vary: 'Accept-Encoding',
ERR! project:design:add         date: 'Wed, 20 Jan 2016 10:15:02 GMT',
ERR! project:design:add         connection: 'close' } } }
```

**Comment by caillou** [comment]
In this case, the problem was that the framework was not up to date and there was a breaking change in the design.
